db:
  restart: always
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=p@assword
    - POSTGRES_DB=team_metrics
  volumes_from:
    - data
data:
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql
  command: "true"
web:
  build: .
  volumes:
      - .:/app/
  ports:
      - "8000:8000"
  links:
    - db
